### ISSUE TITLE
isae-slides.cls

### ISSUE THREAD

**Issue by carlosaguilarmelchor** [tofgarion/supaero-admin#1]
Would it be possible to integrate the isae-slides.cls to this repo ? 
thx
Carlos

**Comment by tofgarion** [comment]
Hi Carlos,

I will create a repository with the ISAE LaTeX classes for lectures as soon as possible :)

Christophe

**Comment by carlosaguilarmelchor** [comment]
Thank you for your nice contributions to the open source community ;)
